"""Module with Object Names class"""


class ObjectNames:
    """Class hold all object names strings"""
    ADD_NEW_ARTICLE_DIALOG = 'add_new_article_dialog'
    ADD_SHOP_DIALOG = 'add_shop_dialog'
    ARTICLES_DIALOG = 'articles_dialog'
    BACKUP_DIALOG = 'backup_dialog'
    CATEGORIES_DIALOG = 'categories_dialog'
    CONFIRM_DIALOG = 'confirm_dialog'
    CREATE_BACKUP_DIALOG = 'create_backup_dialog'
    ERROR_DIALOG = 'error_dialog'
    ADD_ARTICLE_DIALOG_LAYOUT = 'add_articles_dialog_layout'
    ADD_ARTICLE_LAYOUT = 'add_article_layout'
    ADD_SHOP_DIALOG_LAYOUT = 'add_shop_dialog_layout'
    ARTICLES_DIALOG_LAYOUT = 'articles_dialog_layout'
    BACKUP_DIALOG_LAYOUT = 'backup_dialog_layout'
    BACKUP_LAYOUT = 'backup_layout'
    CATEGORIES_DIALOG_LAYOUT = 'categories_dialog_layout'
    SEARCH_ARTICLES_LAYOUT = 'search_articles_layout'
    SHOP_LAYOUT = 'shop_layout'
    SHOPPING_LIST_BUTTONS_LAYOUT = 'shopping_list_buttons_layout'
    SHOPPING_LIST_LAYOUT = 'shopping_list_layout'
    ADD_BUTTON = 'add_button'
    ARTICLES_LIST_BUTTON = 'articles_list_button'
    BACKUP_BUTTON = 'backup_button'
    CANCEL_BUTTON = 'cancel_button'
    CATEGORY_LIST_BUTTON = 'category_list_button'
    CLEAR_LIST_BUTTON = 'clear_list_button'
    EDIT_BUTTON = 'edit_button'
    MOVE_UP_BUTTON = 'move_up_button'
    MOVE_TOP_BUTTON = 'move_top_button'
    MOVE_DOWN_BUTTON = 'move_down_button'
    MOVE_BOTTOM_BUTTON = 'move_bottom_button'
    PRINT_BUTTON = 'print_button'
    REMOVE_BUTTON = 'remove_button'
    REVERT_BUTTON = 'revert_button'
    CATEGORY_COMBO_BOX = 'category_combo_box'
    ARTICLE_COMBO_BOX = 'article_combo_box'
    PRINTER_COMBO_BOX = 'printer_combo_box'
    SHOPS_COMBO_BOX = 'shop_combo_box'
    BASE_TABLE_WIDGET = 'base_table_widget'
    SHOPPING_LIST_TABLE = 'shopping_list_table'
    ARTICLES_LIST_TABLE = 'articles_list_table'
    BACKUP_LIST_WIDGET = 'backup_list_widget'
    CATEGORY_LIST_WIDGET = 'category_list_widget'
    MAIN_WINDOW = 'main_window'
    MAIN_WINDOW_CENTRAL_WIDGET = 'main_window_central_widget'
    CREATE_BACKUP_BUTTON = 'create_backup_button'
